Dbohninx update
daos-stack/lwgrp pull request #3
Opened 2021-01-19 17:53 UTC by daltonbohning

Update to version 1.0.3.
Update packaging to latest.

2021-02-04 18:06 UTC, brianjmurrell requested changes

2021-02-04 18:06 UTC, brianjmurrell commented on lwgrp.spec
> +Release:	4%{?dist}
```suggestion
Release:	1%{?dist}
```

2021-02-04 18:06 UTC, brianjmurrell commented on lwgrp.spec
> +* Tue Jan 19 2021 Dalton A. Bohning <daltonx.bohning@intel.com> - 1.0.3-4
```suggestion
* Tue Jan 19 2021 Dalton A. Bohning <daltonx.bohning@intel.com> - 1.0.3-1
```

2021-02-04 18:41 UTC, brianjmurrell approved these changes

2021-02-04 18:41 UTC, brianjmurrell approved these changes

2021-02-08 15:27 UTC, daltonbohning commented
Order of dependencies:
lwgrp dot version update - This PR
dtcmp dot  version update - (depends on lwgrp) https://github.com/daos-stack/dtcmp/pull/3
mpifileutils minor version update - (depends on dtcmp) https://github.com/daos-stack/mpifileutils-pkg/pull/9

2021-02-08 15:30 UTC, daltonbohning commented
@brianjmurrell I'm unable to add `daos-stack/release-engineering` to this PR, but it is ready to merge, followed by the dependent PRs.

2021-02-08 18:59 UTC, brianjmurrell commented
> @brianjmurrell I'm unable to add `daos-stack/release-engineering` to this PR

Fixed.  It's a shame that GitHub doesn't allow a template projects can model when being created.  Instead we have to remember (or compare with another project) and set forty-eleven configuration items in every new project created.

2021-02-08 19:05 UTC, merged